### ISSUE TITLE
代码写死的URL不支持伪静态的网站

### ISSUE THREAD

**Issue by jason1571** [ciniran/yii2-dic#2]
ciniran/yii2-dic/views/default/index.php第24行

 'remote':'/dic/default/sub.id='+key,

开启了伪静态的网站会报404错误，这一行需要改成

 'remote':'/dic/default/sub.html?id='+key,

为了通用性，建议建议用Url::to(['dic/default/sub', 'id'=>key])来生成链接.

**Comment by ciniran** [comment]
已修复，有问题请再提出

**Comment by jason1571** [comment]
点赞，这修复速度贼快啊！
